gg.jte.development-mode=true
spring.application.name=AI-Labb1

ai.base-url=https://openrouter.ai/api/v1
ai.api-key=${OPENROUTER_API_KEY}
ai.model=z-ai/glm-4.5-air:free

resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
resilience4j.retry.retry-aspect-order=2

resilience4j.retry.instances.openRouterClient.max-attempts=3
resilience4j.retry.instances.openRouterClient.wait-duration=1s
resilience4j.retry.instances.openRouterClient.retry-exceptions=com.example.ailabb1.exception.AiTemporaryException

resilience4j.circuitbreaker.instances.openRouterClient.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.openRouterClient.sliding-window-size=10
resilience4j.circuitbreaker.instances.openRouterClient.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.openRouterClient.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.openRouterClient.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.openRouterClient.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.openRouterClient.record-exceptions=com.example.ailabb1.exception.AiTemporaryException
resilience4j.circuitbreaker.instances.openRouterClient.ignore-exceptions=com.example.ailabb1.exception.AiServiceException
